image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - npm install

stages:
  - test
  - deploy
  
test:
  stage: test
  script:
    - npm run test

deployToAWS:
  only:
    - main
  stage: deploy
  script:
    - bash deploy/deploy.sh

