version: "3"

services:
  bot-server:
    build:
      context: .
    container_name: bot-server
    image: bot-server
    environment:
      - TOKEN=${TOKEN}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "3000:3000"